### ISSUE TITLE
Simplify fonction ideal

### ISSUE THREAD

**Issue by thaos** [v-borse/simulate-classify-plot#11]
https://github.com/v-borse/simulate-classify-plot/blob/e8230d36e2692ab71042880a6d9b0059265e6869/module.py#L256-L266

Could be simplified to something similar to:
`X=X[: -t_steps]`
`Y=X[t_steps:]`

Ne need to transpose probably since its the same dimension order required by  LinearRegression().fit

**Comment by v-borse** [comment]
Yes, the simplified form does more good.
However, transpose may be required since dim would still remain the same but the shape of the matrix will not match later when plotting is to be done

**Comment by thaos** [comment]
I think we dont need to transpose, we just need to subset the data properly
