### ISSUE TITLE
It does not correspond to the formula written by Mathieu!

### ISSUE THREAD

**Issue by thaos** [v-borse/simulate-classify-plot#18]
https://github.com/v-borse/simulate-classify-plot/blob/8177637250f295b89abf7601cc8c7045ef33c862/testLN.py#L169

**Comment by v-borse** [comment]
I used the formula of calculating sum of geometric series but with t_steps+1 which should be t_steps-1.

**Comment by thaos** [comment]
Ok ! Sorry i did not recognize the geometric serie

**Comment by thaos** [comment]
In mathieu's notation, alpha is the slope and beta the intercept. When you call the fonction in your spript you do the reverse.
