### ISSUE TITLE
The second argument of this function should be the true value

### ISSUE THREAD

**Issue by thaos** [v-borse/simulate-classify-plot#20]
https://github.com/v-borse/simulate-classify-plot/blob/8177637250f295b89abf7601cc8c7045ef33c862/testLN.py#L217-L219

**Comment by v-borse** [comment]
Ynrx_rsq = nrx.score(X1[:, 0, None], Ynrx) (ie did thisjust to check how does this vary with predicted value)
and
nrx_rsq = nrx.score(X1[:, 0, None], Y1[:, 0]) (ie, checking with true value)

**Comment by thaos** [comment]
> Ynrx_rsq = nrx.score(X1[:, 0, None], Ynrx) (ie did thisjust to check how does this vary with predicted value)

What you do with this line is comparing nrx.predict(X1[:, 0, None]) with nrx.predict(X2[:, 0, None]). It does not make any sense!
