### ISSUE TITLE
Needs to be computed also on the second trajectory

### ISSUE THREAD

**Issue by thaos** [v-borse/simulate-classify-plot#21]
https://github.com/v-borse/simulate-classify-plot/blob/8177637250f295b89abf7601cc8c7045ef33c862/testLN.py#L202

Also, the function score actually computes the coefficient of determination.

Please provide also the mean root square error of the predictions

**Comment by thaos** [comment]
Additionnaly you can not use the score function for the recursive model when Delta > 1

**Comment by v-borse** [comment]
Ok , so if it doesn't work for recursive then only mean root square error can be calculated then how to calculate coefficient of determination for this case?

**Comment by thaos** [comment]
No both can be calculated, for the recursive model you have to do it by hand, since the linear model you learn only does a forecast a timestep at a time and not directly for a lead time of Delta

**Comment by v-borse** [comment]
Ok.
Should coefficient of determination be computed on a trajectory irrespective of being a test or training trajectory? (X2 being a test trajectory)

**Comment by thaos** [comment]
You can compute the coefficient of determination both on the training and test trajectory. However, you should make the comparison of the predictions and true values on the same trajectory.

**Comment by v-borse** [comment]
Yes, the link shared in the email made the concept clear regarding rmse.
