### ISSUE TITLE
Last iteration does not update Xnew 

### ISSUE THREAD

**Issue by thaos** [v-borse/simulate-classify-plot#24]
https://github.com/v-borse/simulate-classify-plot/blob/dd8bbe411596b8ab7a623db8bb02fe4f33cdbea3/testLN.py#L65-L85

It should be like this, taking into account  #23 

```
def R_predict_multi(Xt,t_steps):
      
    for i in range(t_steps):
        if i == 0:
            Xnew = np.copy(Xt)
        Xnew0 = Rx.predict(Xnew)
        Xnew1 = Ry.predict(Xnew)
        Xnew2 = Rz.predict(Xnew)
        Xnew[:, 0] = Xnew0
        Xnew[:, 1] = Xnew1
        Xnew[:, 2] = Xnew2
         
    return Xnew
```

For https://github.com/v-borse/simulate-classify-plot/blob/dd8bbe411596b8ab7a623db8bb02fe4f33cdbea3/testLN.py#L41-L62

it should be like this:
```
def r_predict_uni(Xt,t_steps):

    for i in range(t_steps):
        if i == 0:
            Xnew = np.copy(Xt)
        Xnew[:, 0] = rx.predict(Xnew[:, 0, None])
        Xnew[:, 1] = rx.predict(Xnew[:, 1, None])
        Xnew[:, 2] = rx.predict(Xnew[:, 2, None])
            
    return Xnew
```

**Comment by v-borse** [comment]
Ok..this is more useful
But for R_predict_multi():

 Xnew[:, 0] = Xnew0
ValueError: could not broadcast input array from shape (10000,1) into shape (10000)

**Comment by thaos** [comment]
You should remove the None here:

https://github.com/v-borse/simulate-classify-plot/blob/dd8bbe411596b8ab7a623db8bb02fe4f33cdbea3/testLN.py#L307-L309
