### ISSUE TITLE
Models should be inputs of the recursive prediction function

### ISSUE THREAD

**Issue by thaos** [v-borse/simulate-classify-plot#25]
https://github.com/v-borse/simulate-classify-plot/blob/2529f51535a019bcc149fd6b052cba48743b4986/testLN.py#L43

rx ry rz should be input

https://github.com/v-borse/simulate-classify-plot/blob/2529f51535a019bcc149fd6b052cba48743b4986/testLN.py#L54

Rx Ry Rz should be input

**Comment by v-borse** [comment]
rx,ry,rz,Rx,Ry,Rz being declared globally can be accessed inside the function definition as well.
The only reason I gave passed Xt as argument is because one can be flexible to test with any test trajectory.

**Comment by thaos** [comment]
Yes but using global variable inside function is bad practice if it can be avoided
